### ISSUE TITLE
example not reproducible

### ISSUE THREAD

**Issue by araujorayza** [robotperf/benchmarks#1] opened 2023-01-09 23:44 UTC
Running the 'reproduction' section in the [first benchmark example](https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a1_perception_2nodes) :

https://github.com/robotperf/benchmarks/blob/609c1cdd470edf15f84354429117f29bdac1f189/benchmarks/perception/a1_perception_2nodes/README.md?plain=1#L25 yields
```bash
[1.034s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'a1_perception_2nodes' in --packages-select
                     
Summary: 0 packages finished [0.43s]
```
There's no a1_perception_2nodes ROS2 package in the repository (no .xml files). Which is confirmed by running
https://github.com/robotperf/benchmarks/blob/609c1cdd470edf15f84354429117f29bdac1f189/benchmarks/perception/a1_perception_2nodes/README.md?plain=1#L28 which gives
```bash
Package 'a1_perception_2nodes' not found: "package 'a1_perception_2nodes' not found, searching: ['/opt/ros/humble']"
```
In the following section, should lines 28 and 31 be the same? The comments state different explanations but the commands are the same.
https://github.com/robotperf/benchmarks/blob/609c1cdd470edf15f84354429117f29bdac1f189/benchmarks/perception/a1_perception_2nodes/README.md?plain=1#L27-L31
Also, the a1_perception_2nodes.launch.py file is missing.

**Comment by vmayoral** [comment] 2023-01-10 08:34
Thanks for reporting! I'll mark this and have a look at it ASAP.

**Comment by vmayoral** [comment] 2023-01-10 14:57
All right, had a few mins to check this. Indeed it's not *reproducible* because there're no source files currently at the https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a1_perception_2nodes package. This is a pending item.

Source code will need to be imported from https://github.com/ros-acceleration/acceleration_examples/tree/main/graphs/perception/perception_2nodes and reworded to meet the naming conventions established [here](https://github.com/robotperf/benchmarks/blob/main/benchmarks/README.md#general-concepts).

Sorry you bumped into this 😭, we're hoping to push an update once we have time for it.

**Comment by vmayoral** [comment] 2023-01-10 14:58
I'll leave this open for now and assigned to me. I'll close this once implementation has been added and tested.

**Comment by araujorayza** [comment] 2023-01-19 14:14
Oh that's ok! Thank you! I will get the source code and try again :)

**Comment by vmayoral** [comment] 2023-01-26 06:24
Sure @jwu1980 and @araujorayza, to manage expectations, I'm wrapping things locally and expect to push this publicly this week or latest Monday next week. Stay tuned to that.

@jwu1980, we have a few ongoing additional benchmarking efforts that align nicely with your [oneAPI PCL work](https://www.intel.com/content/www/us/en/develop/documentation/ei4amr-2022-3-developer-guide/top/tutorials-amr/perception/oneapi_general.html) as well as with [Intel's benchmarking efforts](https://www.intel.com/content/www/us/en/develop/documentation/ei4amr-2022-3-developer-guide/top/tutorials-amr/benchmark_profiling.html). I believe this might be of interest to you. Can you reach out to [me](mailto:victor@accelerationrobotics.com) to have a side chat?

**Comment by vmayoral** [comment] 2023-01-31 09:27
@jwu1980 and @araujorayza, https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a1_perception_2nodes has been updated and tested.

It should be operational and reproducible. Feel free to open this again if you have issues with it.

**Closed by vmayoral** 2023-01-31 09:27 UTC
Labels: bug

**Comment by jwu1980** [comment] 2023-01-31 17:22
Hi, @vmayoral,

Thanks for the update.
The benchmark app gets stuck and never exit.
Any idea?

Thanks.

Best,

Larry

awm@benchmark_ws#RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 launch a1_perception_2nodes trace_a1_perception_2nodes.launch.py
[INFO] [launch]: All log files can be found below /home/awm/.ros/log/2023-01-31-10-15-53-214163-jwu47-desk9-1209436
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tracetools_launch.action]: Writing tracing session to: /home/awm/.ros/tracing/a1_perception_2nodes
[INFO] [component_container-1]: process started with pid [1209450]
[component_container-1] [INFO] [1675185353.551971112] [perception_container]: Load Library: /home/awm/robotic/benchmark_ws/install/lib/libimage_input_component.so
[component_container-1] [INFO] [1675185353.639251260] [perception_container]: Found class: rclcpp_components::NodeFactoryTemplate<robotperf::perception::ImageInputComponent>
[component_container-1] [INFO] [1675185353.639318744] [perception_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<robotperf::perception::ImageInputComponent>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/image_input_component' in container '/perception_container'
[component_container-1] [INFO] [1675185353.645443812] [perception_container]: Load Library: /opt/ros/humble/lib/librectify.so
[component_container-1] [INFO] [1675185353.675174395] [perception_container]: Found class: rclcpp_components::NodeFactoryTemplate<image_proc::RectifyNode>
[component_container-1] [INFO] [1675185353.675213950] [perception_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<image_proc::RectifyNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/benchmark/rectify_node' in container '/perception_container'
[component_container-1] [INFO] [1675185353.677219360] [perception_container]: Load Library: /opt/ros/humble/lib/libresize.so
[component_container-1] [INFO] [1675185353.678061410] [perception_container]: Found class: rclcpp_components::NodeFactoryTemplate<image_proc::ResizeNode>
[component_container-1] [INFO] [1675185353.678073753] [perception_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<image_proc::ResizeNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/benchmark/resize_node' in container '/perception_container'
[component_container-1] [INFO] [1675185353.679862835] [perception_container]: Load Library: /home/awm/robotic/benchmark_ws/install/lib/libimage_output_component.so
[component_container-1] [INFO] [1675185353.680133549] [perception_container]: Found class: rclcpp_components::NodeFactoryTemplate<robotperf::perception::ImageOutputComponent>
[component_container-1] [INFO] [1675185353.680142286] [perception_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<robotperf::perception::ImageOutputComponent>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/image_output_component' in container '/perception_container'

**Comment by vmayoral** [comment] 2023-02-02 15:34
@jwu1980, for what I can see, this launches perfectly fine. In other words, it does not get stucked.

You should be able to see the graph created out of this with rqt or your-other-preferred-visualizer (or the CLI tools).
